function stringToSeed(str) {
	let hash = 0;
	for (let i = 0; i < str.length; i++) {
		hash = str.charCodeAt(i) + ((hash << 5) - hash); // basic hash function. "hash = str.charCodeAt(i) + hash*31" is perfectly fine too.
	}
	return hash;
}

function seededRandom(s) { // linear congruential generator (LCG). Read more here: https://en.wikipedia.org/wiki/Linear_congruential_generator
	let m = 0x80000000; // this is in hexadecimal, or equal to 2^31 in binary or 2147483648 in decimal
	let a = 1664525;
	let c = 1013904223;

	s = s % m; // ensure seed is in the proper range

	return function() {
		s = (a * s + c) % m;
		return s / m; // normalize to [0, 1)
	};
}

let seed = "Paul"; // fixed seed value, change this to change the numbers generated by the seed. Seed must be a string
let num = seededRandom(stringToSeed(seed));

for(let i = 0; i < 5; i++) {
	console.log(num());
}

/*

====//stringToSeed("Paul") Output//====

str.charCodeAt(x) returns the ASCII/Unicode value of the character in the argument.
str.charCodeAt(0) is "P" which is 80. "a" is 97, "u" is 117, "l" is 108.

hash starts at 0. use this formula

hash = str.charCodeAt(i) + ((hash << 5) - hash);

Plug in the values. Start with charcode for "P"

hash = 80 + ((hash << 5) - hash)
hash = 80 + ((0 << 5) - 0)
hash = 80

Now, loop for "a"

hash = 97 + ((80 << 5) - 80) // 80 << 5 is the same as 80 * 2^5, or 80*32
hash = 97 + ((2560) - 80)
hash = 97 + 2480
hash = 2577

Now, loop for "u"

hash = 117 + ((2577 << 5) - 2577) // again, 2577 << 5 is 2577*32
hash = 117 + ((82464) - 2577)
hash = 117 + 79887
hash = 80004

Now, loop for "l", last loop

hash = 108 + ((80004 << 5) - 80004)
hash = 108 + ((80004*32) - 80004)
hash = 108 + ((2560128) - 80004)
hash = 108 + 2480124
hash = 2480232

====//seededRandom(2480232) Output//====

Plugging our hash value of 2480232 from before into this function...

s = s % m
s = 2480232 % 2147483648 (variable 's' stays the same)
s = 2480232

Then, in the return function we use this formula...

s = (a * s + c) % m

Order of operations... first a * s, then + c, then % m

s = (1664525 * 2480232 + 1013904223) % 2147483648
s = (4128408169800 + 1013904223) % 2147483648
s = 4129422074023 % 2147483648
s = 1958502567

return s / m
return 1958502567 / 2147483648 = 0.91199

So our first value from the PRNG is going to be 0.91199
The second value can be calculated by using 1958502567 as the 's' value, shown below. This is the last value that 's' was set to, NOT the s/m(0.91199) value that was returned.

s = (a * s + c) % m
s = (1664525 * 1958502567 + 1013904223) % 2147483648
s = (3259976485335675 + 1013904223) % 2147483648
s = 3259977499239898 % 2147483648
s = 684811738

return s / m
return 684811738 / 2147483648 = 0.31889

This is the second number generated, 0.31889. Continue this pattern for as many numbers as you want to generate.

*/